version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  #install:
    #commands:
      # - command
      # - command
    #finally:
      # - command
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
    #finally:
      # - command
      # - command
  build:
    commands:
      - alias composer="php /usr/local/bin/composer" && composer install --ignore-platform-reqs && echo $PWD && echo "files in current dir" && ls -l
      - mkdir code_output
      - echo "move all content to code_output dir"
      - find . ! -regex '.*/code_output' ! -regex '.' -exec cp -r '{}' code_output \;
      - echo "zip code_output"
      - zip -r code_output.zip code_output && ls -l && echo $PWD
    #finally:
      # - command
      # - command
  #post_build:
    #commands:
      # - command
      # - command
    #finally:
      # - command
      # - command
artifacts:
  discard-paths: no
  files:
    - code_output.zip
  base-directory: '*'
  

